require("symbols-outline").setup({
  fold_markers = { '>', '>' },
  symbols = {
    File = {icon = "file", hl = "URI"},
    Module = {icon = "mod", hl = "Namespace"},
    Namespace = {icon = "namespace", hl = "Namespace"},
    Package = {icon = "package", hl = "Namespace"},
    Class = {icon = "class", hl = "Type"},
    Method = {icon = "method", hl = "Method"},
    Property = {icon = "property", hl = "Method"},
    Field = {icon = "field", hl = "Field"},
    Constructor = {icon = "constructor", hl = "Constructor"},
    Enum = {icon = "enum", hl = "Type"},
    Interface = {icon = "interface", hl = "Type"},
    Function = {icon = "function", hl = "Function"},
    Variable = {icon = "variable", hl = "Constant"},
    Constant = {icon = "constant", hl = "Constant"},
    String = {icon = "string", hl = "String"},
    Number = {icon = "number", hl = "Number"},
    Boolean = {icon = "bool", hl = "Boolean"},
    Array = {icon = "array", hl = "Constant"},
    Object = {icon = "obj", hl = "Type"},
    Key = {icon = "key", hl = "Type"},
    Null = {icon = "null", hl = "Type"},
    EnumMember = {icon = "enum-member", hl = "Field"},
    Struct = {icon = "struct", hl = "Type"},
    Event = {icon = "event", hl = "Type"},
    Operator = {icon = "op", hl = "Operator"},
    TypeParameter = {icon = "type-param", hl = "Parameter"}
  }
})
